# Generated by Django 3.2.9 on 2021-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RP', 'regular pizza'), ('SP', 'siciliam pizza'), ('To', 'tippings'), ('Su', 'subs'), ('Pa', 'pasta'), ('Di', 'dinner platters')], max_length=5)),
                ('name', models.TextField(max_length=50)),
                ('size', models.CharField(blank=True, choices=[('SM', 'small'), ('LG', 'large')], max_length=5)),
                ('price_1', models.FloatField()),
                ('price_2', models.FloatField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
