# Generated by Django 3.2.9 on 2021-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='extras',
            field=models.TextField(blank=True),
        ),
    ]
