# Generated by Django 3.2.9 on 2021-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
