# Generated by Django 3.2.9 on 2021-12-20 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_product_price_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amoun', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra', models.IntegerField()),
                ('extras', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='amoun',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='product',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('RP', 'regular pizza'), ('SP', 'siciliam pizza'), ('To', 'toppings'), ('Su', 'subs'), ('Pa', 'pasta'), ('Di', 'dinner platters')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'small'), ('LG', 'large')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.menuitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
    ]
